title: "Naa Odey Solomon"
description: "MPhil in Mathematical Statistics | Bayesian Inference | Time Series"
url: "https://naaodey.github.io"
baseurl: ""
theme: minima

# Navigation links
header_pages:
  - about.md
  - projects.md
  - blog.md
  - contact.md

# Markdown
markdown: kramdown
